[app]
base_url = "http://localhost:8501"

[admin]
email = "admin@exemplo.com"
password = "trocar123"
name = "Admin"

[stripe]
secret_key = "sk_test_xxx"
publishable_key = "pk_test_xxx"
price_id = "price_xxx"

[database]
url = ""
