[app]
base_url = "https://gera-senhas.streamlit.app"  # troque depois do deploy

[admin]
email = "pauloqxm@gmail.com"
password = "trocar123"
name = "Admin"

[stripe]
secret_key = "sk_test_..."   # chave secreta
publishable_key = "pk_test_..."
price_id = "price_..."       # do produto/preço criado no Stripe

[database]
url = ""  # vazio usa SQLite; em produção use um Postgres (ex: Neon) e defina DATABASE_URL
